[feature] Added OpenVPN  auth_nocache
openwisp/netjsonconfig pull request #215
Opened 2022-02-23 09:14 UTC by aagman945

Added  ```auth_nocache``` to OpenVPN

closes #177

2022-02-23 19:30 UTC, pandafy requested changes
@aagman945 this PR will need some more work before merging. 

We will need to  update the `auto_client` function of OpenVpn class to add `auth_nocache` field. 

https://github.com/openwisp/netjsonconfig/blob/a90813c263dd23e56d2a2f8ef008c7135dbfee05/netjsonconfig/backends/openvpn/openvpn.py#L23-L34

Adding `auth_nocache` in the `copy_keys` list should do it. 

We will also need to update [tests](https://github.com/openwisp/netjsonconfig/blob/master/tests/openvpn/test_backend.py) after 
making this change. In the tests, set the value of `auth_nocache` to `True`. 

The [documentation](https://github.com/openwisp/netjsonconfig/blob/master/docs/source/backends/openvpn.rst#openvpn-backend-schema) needs to be updated as well to reflect addition of this field.

2022-02-23 19:30 UTC, pandafy commented on netjsonconfig/backends/openvpn/schema.py
> +                    "inputs after they are used",
```suggestion
                    "description": (
                        "Cause OpenVPN to immediately forget username/password"
                        "inputs after they are used"
                    ),
```

2022-02-24 06:06 UTC, aagman945 commented
@pandafy should I update all the tests, or  just ```test_server_mode``` & ```test_client_mode``` .

2022-03-03 16:38 UTC, pandafy requested changes
Good work @aagman945, everything looks good to me. I have tested this with openwisp-controller as well. 
The only problem I see is with the commit message. The commit message does not reference the issue. Read the commit style guideline here https://openwisp.io/docs/developer/contributing.html#how-to-commit-your-changes-properly

Also, can you squash you commits and rebase you PR on the latest master?

2022-03-04 05:51 UTC, aagman945 commented
> Good work @aagman945, everything looks good to me. I have tested this with openwisp-controller as well. The only problem I see is with the commit message. The commit message does not reference the issue. Read the commit style guideline here https://openwisp.io/docs/developer/contributing.html#how-to-commit-your-changes-properly
> 
> Also, can you squash you commits and rebase you PR on the latest master?
@pandafy Sorry ,My bad
Done with the required changes

2022-03-04 11:49 UTC, pandafy requested changes
@aagman945 the build is failing!

2022-03-07 10:32 UTC, pandafy approved these changes
LGTM! 👍🏼 

@aagman945 the first word of the commit description should be capitalised ("Closes" and not "closes"). This time, we will update the description while merging. But if you are eager to continue contributing to OpenWISP, I ask you to please take care of these small details from next time. 

Thanks for contributing! 

Deferring merge to @nemesisdesign 😄

2022-03-07 15:12 UTC, aagman945 commented
> LGTM! 👍🏼
> 
> @aagman945 the first word of the commit description should be capitalised ("Closes" and not "closes"). This time, we will update the description while merging. But if you are eager to continue contributing to OpenWISP, I ask you to please take care of these small details from next time.
> 
> Thanks for contributing!
> 
> Deferring merge to @nemesisdesign smile

I'll take  care from next time.

2022-03-07 20:56 UTC, nemesisdesign approved these changes

2022-03-07 20:56 UTC, merged