[feature] Added support for OpenVPN tls-auth option #174
openwisp/netjsonconfig pull request #217
Opened 2022-03-08 13:01 UTC by pandafy

The OpenVPN backend will automatically create a file for the
key present in "tls_auth" field and update the value of the
"tls-auth" parameter.

Closes #174

2022-03-08 21:18 UTC, nemesisdesign requested changes
Good progress, see below.

2022-03-08 21:18 UTC, nemesisdesign commented on netjsonconfig/backends/openvpn/schema.py
> +                    "propertyOrder": 53,
Let's add `"format": "textarea",` to display it as a textarea in the UI.

2022-03-08 21:18 UTC, nemesisdesign commented on netjsonconfig/backends/openvpn/converters.py
> +            ca_path = config.get('ca', '')
this code is a bit unclear, are you using the ca path to determine where to put the file? Let's make this clearer.

2022-03-08 21:18 UTC, nemesisdesign commented on netjsonconfig/backends/openvpn/converters.py
> +            tls_auth_path = '/'.join(ca_path.split('/')[:-1] + ['tls_auth.key'])
What if there's multiple VPN servers or clients, do the files collide? If yes, please add a test for this and make sure the tls key is unique (eg: each config has a name which can be used for this).

2022-03-09 15:05 UTC, nemesisdesign requested changes

2022-03-09 15:05 UTC, nemesisdesign commented on docs/source/backends/openvpn.rst
> +| ``tls_auth``             | string  |              | string containing TLS Auth key                              |
let's move this after `tls_cipher`, in general, let's add new options where they make sense, not just at the end.

2022-03-09 15:59 UTC, nemesisdesign requested changes
I see two issues.

1. the result in OpenWISP Controller doesn't match what I would expect

![Screenshot from 2022-03-09 12-55-56](https://user-images.githubusercontent.com/841044/157479375-1441b121-f68d-43cb-bd48-f8e761568fc1.png)

2. I tried creating a server with the TLS auth key, then created the template client, but suprisingly the TLS auth key on the client was not autogenerated. Please add a specific test for the auto client feature.

Please pull my changes: 4145fc129d4a4d52203ae540d98891bcecc3d4a0.

2022-03-09 16:13 UTC, pandafy commented on netjsonconfig/backends/openvpn/schema.py
> +                    "propertyOrder": 18,
It has same `propertyOrder` as `crl_verify`. 

https://github.com/openwisp/netjsonconfig/blob/f2e692cee7d3a26b59c3a8143ddfcbc97816445c/netjsonconfig/backends/openvpn/schema.py#L622-L628

2022-03-09 16:50 UTC, pandafy commented
VPN server 
![Screenshot from 2022-03-09 22-08-23](https://user-images.githubusercontent.com/32094433/157489227-a1f154b6-3def-4e40-bcb3-7482cb1ad80a.png)

VPN Client Template 
![Screenshot from 2022-03-09 22-11-38](https://user-images.githubusercontent.com/32094433/157489265-7baed1ea-0d9d-40c3-a0cb-d93c3d2ddc07.png)
![Screenshot from 2022-03-09 22-11-54](https://user-images.githubusercontent.com/32094433/157489281-0a756b1e-3504-45af-bf1f-2f23014052d4.png)

Device
![Screenshot from 2022-03-09 22-19-41](https://user-images.githubusercontent.com/32094433/157490029-a53414ac-3288-4c04-9481-67e00958f0fa.png)
![Screenshot from 2022-03-09 22-19-52](https://user-images.githubusercontent.com/32094433/157490037-0e872e41-cbe2-4e62-9168-0e686e200a7a.png)

2022-03-10 15:47 UTC, nemesisdesign approved these changes

2022-03-10 15:58 UTC, merged