[feature] Add OWE encryption type
openwisp/netjsonconfig pull request #255
Opened 2023-02-28 09:42 UTC by Aryamanz29

Related to : https://github.com/openwisp/netjsonconfig/pull/251

2023-02-28 13:31 UTC, nemesisdesign commented
Please reference the issue: https://github.com/openwisp/netjsonconfig/issues/193

2023-02-28 18:28 UTC, nemesisdesign requested changes
This patch misses at least 1 render and 1 parse tests.

2023-02-28 18:28 UTC, nemesisdesign commented on netjsonconfig/schema.py
> +                            "title": "encryption protocol",
```suggestion
                            "title": "Opportunistic Wireless Encryption",
```

2023-02-28 18:28 UTC, nemesisdesign commented on netjsonconfig/schema.py
> +                            "options": {"enum_titles": ["OWE"]},
```suggestion
                            "options": {"enum_titles": ["Opportunistic Wireless Encryption"]},
```

2023-03-01 12:49 UTC, kellerman commented
If you want to do the transitioning to OWE/Open systems, then yes, these options also have to be supported:
owe_transition_ssid,option owe_transition_bssid,owe_transition_ifname
And maybe some more options, from a quick tell...
I personally don't use transitioning, It didn't work quite well for me.

2023-05-04 16:33 UTC, nemesisdesign approved these changes
I had to make a few adjustments in bfff240.

2023-05-04 16:34 UTC, merged

2023-05-04 16:34 UTC, nemesisdesign commented
Thanks @kellerman @Aryamanz29 :+1: :clap: :fire: