[feature] Added support for more WPA EAP client parameters #313
openwisp/netjsonconfig pull request #318
Opened 2024-09-20 17:45 UTC by pandafy

## Checklist

- [x] I have read the [OpenWISP Contributing Guidelines](http://openwisp.io/docs/developer/contributing.html).
- [x] I have manually tested the changes proposed in this pull request.
- [ ] I have written new test cases for new code and/or updated existing tests for changes to existing code.
- [ ] I have updated the documentation.

## Reference to Existing Issue

Closes #313

2024-09-25 17:21 UTC, nemesifier requested changes
Docs are missing here.

2024-09-27 17:43 UTC, pandafy commented
I don't see a table explaining the WPA client parameters 
Shall I add the options here in the example?

https://netjsonconfig.openwisp.org/en/latest/backends/openwrt.html#wpa2-enterprise-802-1x-client

2024-09-27 18:33 UTC, nemesifier commented
> I don't see a table explaining the WPA client parameters Shall I add the options here in the example?
> 
> https://netjsonconfig.openwisp.org/en/latest/backends/openwrt.html#wpa2-enterprise-802-1x-client

Yes please.

2024-11-07 21:02 UTC, nemesifier approved these changes

2024-11-07 21:02 UTC, merged